---
environment_proxy: /etc/environment
proxy:
    - http_proxy: "{{ proxy_address }}"
    - https_proxy: "{{ proxy_address }}"
    - ftp_proxy: "{{ proxy_address }}"
    - 'no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au'

#remember to change the IP address
masterNode: 45.113.233.239

slaveNode0: 45.113.233.215

slaveNode1: 45.113.234.122

nginxNode: 45.113.235.61